### ISSUE TITLE
2022-03-09 11:01:04.709 Uncaught app exception

### ISSUE THREAD

**Issue by soft-nougat** [soft-nougat/dqw-ivves_structured#3]
2022-03-09 11:01:04.709 Uncaught app exception

Traceback (most recent call last):

  File "/home/appuser/venv/lib/python3.7/site-packages/streamlit/script_runner.py", line 379, in _run_script

    exec(code, module.__dict__)

  File "/app/dqw-ivves_structured/app.py", line 46, in <module>

    structured_data_app()

  File "/app/dqw-ivves_structured/tabular_eda/structured_data.py", line 72, in structured_data_app

    analyse_file(st.session_state.data)

  File "/app/dqw-ivves_structured/tabular_eda/structured_data.py", line 258, in analyse_file

    st_profile_report(pr)

  File "/home/appuser/venv/lib/python3.7/site-packages/streamlit_pandas_profiling/__init__.py", line 54, in st_profile_report

    _render_component(html=report.to_html(), height=height, key=key, default=None)

  File "/home/appuser/venv/lib/python3.7/site-packages/pandas_profiling/profile_report.py", line 368, in to_html

    return self.html

  File "/home/appuser/venv/lib/python3.7/site-packages/pandas_profiling/profile_report.py", line 185, in html

    self._html = self._render_html()

  File "/home/appuser/venv/lib/python3.7/site-packages/pandas_profiling/profile_report.py", line 287, in _render_html

    report = self.report

  File "/home/appuser/venv/lib/python3.7/site-packages/pandas_profiling/profile_report.py", line 179, in report

    self._report = get_report_structure(self.config, self.description_set)

  File "/home/appuser/venv/lib/python3.7/site-packages/pandas_profiling/report/structure/report.py", line 247, in get_report_structure

    render_variables_section(config, summary),

  File "/home/appuser/venv/lib/python3.7/site-packages/pandas_profiling/report/structure/report.py", line 102, in render_variables_section

    render_map[summary["type"]](config, template_variables)

  File "/home/appuser/venv/lib/python3.7/site-packages/pandas_profiling/report/structure/variables/render_real.py", line 122, in render_real

    mini_histogram(config, *summary["histogram"]),

  File "/usr/local/lib/python3.7/contextlib.py", line 74, in inner

    return func(*args, **kwds)

  File "/home/appuser/venv/lib/python3.7/site-packages/pandas_profiling/visualisation/plot.py", line 113, in mini_histogram

    return plot_360_n0sc0pe(config)

  File "/home/appuser/venv/lib/python3.7/site-packages/pandas_profiling/visualisation/utils.py", line 66, in plot_360_n0sc0pe

    plt.savefig(image_str, format=image_format)

  File "/home/appuser/venv/lib/python3.7/site-packages/matplotlib/pyplot.py", line 859, in savefig

    res = fig.savefig(*args, **kwargs)

  File "/home/appuser/venv/lib/python3.7/site-packages/matplotlib/figure.py", line 2311, in savefig

    self.canvas.print_figure(fname, **kwargs)

  File "/home/appuser/venv/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 2217, in print_figure

    **kwargs)

  File "/home/appuser/venv/lib/python3.7/site-packages/matplotlib/backends/backend_svg.py", line 1329, in print_svg

    self._print_svg(filename, fh, **kwargs)

  File "/home/appuser/venv/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 1639, in wrapper

    return func(*args, **kwargs)

  File "/home/appuser/venv/lib/python3.7/site-packages/matplotlib/backends/backend_svg.py", line 1353, in _print_svg

    self.figure.draw(renderer)

  File "/home/appuser/venv/lib/python3.7/site-packages/matplotlib/artist.py", line 41, in draw_wrapper

    return draw(artist, renderer, *args, **kwargs)

  File "/home/appuser/venv/lib/python3.7/site-packages/matplotlib/figure.py", line 1864, in draw

    renderer, self, artists, self.suppressComposite)

  File "/home/appuser/venv/lib/python3.7/site-packages/matplotlib/image.py", line 131, in _draw_list_compositing_images

    a.draw(renderer)

  File "/home/appuser/venv/lib/python3.7/site-packages/matplotlib/artist.py", line 41, in draw_wrapper

    return draw(artist, renderer, *args, **kwargs)

  File "/home/appuser/venv/lib/python3.7/site-packages/matplotlib/cbook/deprecation.py", line 411, in wrapper

    return func(*inner_args, **inner_kwargs)

  File "/home/appuser/venv/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 2747, in draw

    mimage._draw_list_compositing_images(renderer, self, artists)

  File "/home/appuser/venv/lib/python3.7/site-packages/matplotlib/image.py", line 131, in _draw_list_compositing_images

    a.draw(renderer)

  File "/home/appuser/venv/lib/python3.7/site-packages/matplotlib/artist.py", line 41, in draw_wrapper

    return draw(artist, renderer, *args, **kwargs)

  File "/home/appuser/venv/lib/python3.7/site-packages/matplotlib/axis.py", line 1169, in draw

    tick.draw(renderer)

  File "/home/appuser/venv/lib/python3.7/site-packages/matplotlib/artist.py", line 41, in draw_wrapper

    return draw(artist, renderer, *args, **kwargs)

  File "/home/appuser/venv/lib/python3.7/site-packages/matplotlib/axis.py", line 291, in draw

    artist.draw(renderer)

  File "/home/appuser/venv/lib/python3.7/site-packages/matplotlib/artist.py", line 41, in draw_wrapper

    return draw(artist, renderer, *args, **kwargs)

  File "/home/appuser/venv/lib/python3.7/site-packages/matplotlib/text.py", line 729, in draw

    ismath=ismath, mtext=mtext)

  File "/home/appuser/venv/lib/python3.7/site-packages/matplotlib/backends/backend_svg.py", line 1257, in draw_text

    self._draw_text_as_path(gc, x, y, s, prop, angle, ismath, mtext)

  File "/home/appuser/venv/lib/python3.7/site-packages/matplotlib/backends/backend_svg.py", line 1072, in _draw_text_as_path

    font, s, glyph_map=glyph_map, return_new_glyphs_only=True)

  File "/home/appuser/venv/lib/python3.7/site-packages/matplotlib/textpath.py", line 161, in get_glyphs_with_font

    for char, (_, x) in zip(s, _text_layout.layout(s, font)):

  File "/home/appuser/venv/lib/python3.7/site-packages/matplotlib/_text_layout.py", line 35, in layout

    glyph = font.load_glyph(glyph_idx, flags=LOAD_NO_HINTING)

RuntimeError: In load_glyph: Could not load glyph (error code 0x14)

**Comment by soft-nougat** [comment]
Glyph error creating pdfs and saving images https://github.com/matplotlib/matplotlib/issues/13723/
